# Generated by Django 4.0.5 on 2022-07-05 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phoneConfirmationCode',
            field=models.IntegerField(blank=True),
        ),
    ]
