# Generated by Django 4.0.2 on 2022-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_author_name_alter_author_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
