# Generated by Django 4.0.5 on 2022-06-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0002_alter_privateroom_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='archived',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
