# Generated by Django 4.0.5 on 2022-06-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_video_archived_video_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='isEmailConfirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='author',
            name='isPhoneConformed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
