# Generated by Django 4.0.2 on 2022-04-30 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0004_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='privateroom',
            name='privateChat',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
