# Generated by Django 4.0.5 on 2022-06-16 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_author_socialacc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='socialAcc',
        ),
    ]
