# Generated by Django 4.0.5 on 2022-06-17 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0007_remove_author_socialacc'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='socialAcc',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
